config/routes.rb
Probbler::Application.routes.draw do

  	devise_for :users

	root :to => "problems#index"

	resources :problems

	match 'problems/:id/add_voice', to: 'problems#add_voice', :via => [:get, :patch]

end

app/models/problem.rb
class Problem < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
	before_action :set_problem, only: [:show, :edit, :update, :destroy, :add_voice]

	# GET /problems
	# GET /problems.json
	def index
		@problems = Problem.all
		@problem = Problem.new
	end

	# GET /problems/1
	# GET /problems/1.json
	def show
	end

	# GET /problems/1/edit
	def edit
	end

	# POST /problems
	# POST /problems.json
	def create
		@problem = Problem.new(problem_params)

		respond_to do |format|
			if @problem.save
				format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
				format.json { render action: 'show', status: :created, location: @problem }
			else
				format.html { render action: 'new' }
				format.json { render json: @problem.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /problems/1
	# PATCH/PUT /problems/1.json
	def update
		respond_to do |format|
			if @problem.update(problem_params)
				format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @problem.errors, status: :unprocessable_entity }
			end
		end
	end

	def add_voice
		@problem.backers = @problem.backers + 1
		respond_to do |format|
			if @problem.save
				format.html { redirect_to @problem, notice: 'Problem was successfully upvoted.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @problem.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /problems/1
	# DELETE /problems/1.json
	def destroy
		@problem.destroy
		respond_to do |format|
			format.html { redirect_to problems_url }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_problem
			@problem = Problem.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def problem_params
			params.require(:problem).permit(:title, :description, :backers)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Probbler</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>

	<footer>
		<% if user_signed_in? %>
			<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<%else%>
			<%= link_to 'Sign Up!', new_user_registration_path %>
			<%= link_to 'Sign In', new_user_session_path %>
		<%end%>
	</footer>
</body>
</html>

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
<!--   <div class="field"> -->
    <%= f.hidden_field :backers, :value => 1 %>
<!--   </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<h1>New problem</h1>

<%= render 'form' %>

<h1>Other problems</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Backers</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= problem.title %></td>
        <td><%= problem.description %></td>
        <td><%= problem.backers %></td>
        <td><%= link_to 'Show', problem %></td>
        <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
        <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @problem.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @problem.description %>
</p>

<p>
  <strong>Backers:</strong>
  <%= @problem.backers %>
</p>

<%= link_to 'Add Voice', "/problems/#{@problem.id}/add_voice" %>
<%= link_to 'Edit', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %>